version: '3.8'

services:
  ros2_camera_container:
    image: ${DOCKER_REGISTRY_ADDR}/${DOCKER_IMAGE_NAME}:latest
    container_name: ${DOCKER_CONTAINER_NAME}
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - /dev/:/dev
      - /run/udev:/run/udev
    network_mode: host
    command: ["/bin/bash", "-c", "source /camera_ws/install/setup.bash; source /ros2_ws/install/setup.bash; ros2 launch waver_physical_bringup main.launch.py"]
    restart: always
